# Generated by Django 5.1.7 on 2025-04-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 16, 16, 57, 933286, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user_id', 'question_id')},
        ),
    ]
